momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  end-point: https://test-payment.momo.vn/v2/gateway/api
  return-url: http://localhost:8080/api/payments/call-back
  ipn-url: http://localhost:8080/api/payments/call-back
  request-type: payWithMethod
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnaeasyswp@gmail.com
    password: vzmg jzmt gsqv ugki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
ghn:
  token: 5fb05b03-fc2a-11f0-84e6-16a0a09c770f
  shopId: 6241154
  url-fee: https://online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
  length: 15
  width: 15
  height: 5
  weight: 300
  service_id: 53321



